# Generated by Django 4.0.4 on 2022-05-29 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todolist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('important', models.BooleanField(default=False, verbose_name='Важное дело')),
                ('public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(default=todolist.models.get_time_plus_day, verbose_name='Время завершения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Активная'), (0, 'Отложенная'), (2, 'Выполнено')], default=1, verbose_name='Статус')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='todolist.todolist')),
            ],
        ),
    ]
