# Generated by Django 4.0.4 on 2022-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Дело', 'verbose_name_plural': 'Дела'},
        ),
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активная'), (0, 'Отложенная'), (2, 'Выполнено')], default=1, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='TodoStatus',
        ),
    ]
